node {
  stage 'Checkout Code'
  checkout scm
  
  stage 'Build'
  openshiftBuild(buildConfig: 'flask-demo', showBuildLogs: 'true')
  
  stage 'Deploy'
  openshiftDeploy(deploymentConfig: 'flask-demo')
}

